.travis.yml:
  # disable rubocop for now
  remove_includes:
    - env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
  includes:
    - env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file syntax lint metadata_lint"
      stage: static

    # enable acceptance testing
    - stage: acceptance
      install:
        - bundle install
        - wget https://github.com/purpleidea/mgmt/releases/download/0.0.19/mgmt_0.0.19_amd64.deb
        - dpkg -i mgmt_0.0.19_amd64.deb
      script:
        - acceptance/run_test.sh
