name: Spec tests
run-name: ${{ github.actor }} pushed some commits
on: [push, pull_request]
jobs:
  rspec:
    strategy:
      matrix:
        gemfile: [ puppet5, puppet6, puppet7, puppet8 ]
        os: [ ubuntu-latest, macos-latest ]
        include:
        - ruby: 2.6.3
        - gemfile: puppet8
          ruby: 3.2
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
